Add watchOS support to cocoapods
parse-community/ParseLiveQuery-iOS-OSX pull request #235
Opened 2020-11-15 14:48 UTC by cbaker6

2020-11-15 19:14 UTC, cbaker6 commented
Note that Travis seems to be having some issues with Xcode builds, but I don't see the issue listed on travis. You may have to rerun the travis build if it fails to start

2020-11-16 16:34 UTC, drdaz approved these changes
Looks great.

2020-11-16 16:44 UTC, drdaz requested changes
Actually... the changelog needs an entry

2020-11-16 16:54 UTC, drdaz approved these changes

2020-11-16 18:29 UTC, TomWFox requested changes

2020-11-16 18:29 UTC, TomWFox commented on CHANGELOG.md
>  [Full Changelog](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/compare/2.7.2...master)
```suggestion
[Full Changelog](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/compare/2.7.3...master)
```

2020-11-16 18:36 UTC, TomWFox approved these changes

2020-11-16 19:09 UTC, merged

2020-11-16 19:34 UTC, cbaker6 commented
@TomWFox @drdaz can one of you push the pods? It looks like it failed to deploy and didn't give much info about the failure.

2020-11-16 20:13 UTC, cbaker6 commented
@TomWFox do you if the COCOAPODS_TRUNK_TOKEN is set? Travis us giving this “ [!] You need to run `pod trunk register` to register a session first.”

2020-11-16 20:20 UTC, TomWFox commented
It is set, it has probably just expired - they do that periodically

2020-11-16 20:24 UTC, TomWFox commented
Fairly sure the deployment is broken anyway because it work for the last release either

2020-11-17 00:14 UTC, cbaker6 commented
I tried a few different things in travis, but couldn't get it to go. I agree that the deployment seems broken.

I add this branch to push the pod manually for 2.7.3, https://github.com/parse-community/ParseLiveQuery-iOS-OSX/tree/2.7.3-pod

2020-11-17 00:43 UTC, cbaker6 commented
I found the problem...

During PR's to the master branch travis shows the following environment vars setup in the travis build log:

```
Setting environment variables from repository settings
139$ export GITHUB_TOKEN=[secure]
140$ export COCOAPODS_TRUNK_TOKEN=[secure]
```

I think the In the `COCOAPODS_TRUNK_TOKEN` isn't enabled for `tags` as it doesn't show in the logs anymore, the environment variable is missing. @TomWFox can you try to completely delete it and add it back enabling it for tags?
https://travis-ci.com/github/parse-community/ParseLiveQuery-iOS-OSX/jobs/441073847#L134
```
Setting environment variables from repository settings
134$ export GITHUB_TOKEN=[secure]
```

2020-11-17 01:10 UTC, cbaker6 commented
I think the `Only available to the master branch` is what's blocking it from tags. Setting it to `Available to all branches` should fix it

2020-11-17 20:21 UTC, TomWFox commented
Sorry for the lack of response here, I've been having all sorts of issues with my shell since updating to Big Sur 🤦

@drdaz Can you get a new trunk token and put it in travis?

2020-11-18 08:10 UTC, drdaz commented
I'll see if I can figure that out later today 😃

2020-11-18 19:56 UTC, drdaz commented
I've updated the token in Travis and made it 'Available to all branches'.

2020-11-18 21:08 UTC, TomWFox commented
Thanks!

2020-11-18 21:09 UTC, cbaker6 commented
I was able to deploy 2.7.3 and 2.8.0 via Travis by re-running the respective builds. The good thing about Travis is it can rerun the exact same build while pulling the latest env vars. We shouldn’t have an issue pushing via tags and Travis as long as the token doesn’t expire.

Also, the docs are deploying again via Travis and jazzy. Only thing is, the code in this repo is currently undocumented. I made the web link align with the iOS and Swift repos, http://parseplatform.org/ParseLiveQuery-iOS-OSX/api/

2020-11-18 21:21 UTC, TomWFox commented
Awesome. The token expires after some period (a couple months roughly) if not used which is likely on this repo. I believe all that is needed is to run `pod trunk me` periodically which could be done with a Cron job.

2020-11-18 21:26 UTC, cbaker6 commented
I’ve seen cron in Travis, but I’ve never tried it. I wonder if setting the pod token to the same value as the iOS SDK (and eventually the Parse-Swift SDK) will fix the expiration problem since at least 1 of these should release within a 2 month period?

2020-11-18 21:32 UTC, TomWFox commented
Thats definitely a good idea. I think it would still be reasonably conceivable for the token to expire but with the same token in each we could have one Cron job as an insurance.